### ISSUE TITLE
CombineLayers panics when merging layer with checks onto one without

### ISSUE THREAD

**Issue by benhoyt** [canonical/pebble#132]
[gbeuzeboc](https://launchpad.net/~gbeuzeboc) described this issue on Mattermost -- opening a GitHub issue here to track.

Hello, I have been giving Pebble a try to see if we could use it to orchestrate some robotics applications and I have few question.
The first one is regarding Checks. I have one service and one check (each one defined in a different layer). If my check fails I want my service to restart but pebble seems to crash:

```
# 001-layer.yaml
summary: Simple layer

description: |
    A better description for a simple layer.

services:
    srv1:
        override: replace
        command: bash -c 'while :; do echo "srv1 is running"; sleep 1; done'
        startup: enabled
```

```
# 002-layer2.yaml
summary: Simple layer

description: |
    Another one

services:
    srv1:
        override: merge
        on-check-failure:
            mycustomcheck: restart

checks:
    mycustomcheck:
        override: replace
        exec:
            command: bash -c 'sleep 1; exit 1'
```

If I run pebble over this config I get:

```
2022-08-08T17:08:36.114Z [pebble] Started daemon.
2022/08/08 19:08:36 http: panic serving pid=3934413;uid=1000;socket=/tmp/pebble/.pebble.socket;: assignment to entry in nil map
goroutine 51 [running]:
net/http.(*conn).serve.func1(0xc00023a000)
        /usr/lib/go-1.13/src/net/http/server.go:1767 +0x139
panic(0x8bc980, 0x9ee260)
        /usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
github.com/canonical/pebble/internal/plan.(*Service).Merge(0xc0002783c0, 0xc000278140)
        /home/guillaume/code/misc/pebble/internal/plan/plan.go:160 +0x5d0
github.com/canonical/pebble/internal/plan.CombineLayers(0xc000212710, 0x2, 0x2, 0x2, 0x2, 0x0)
        /home/guillaume/code/misc/pebble/internal/plan/plan.go:420 +0x3de
github.com/canonical/pebble/internal/plan.ReadDir(0xc0000223c7, 0xb, 0x521ed2, 0x890e20, 0x0)
        /home/guillaume/code/misc/pebble/internal/plan/plan.go:841 +0x1d6
github.com/canonical/pebble/internal/overlord/servstate.(*ServiceManager).reloadPlan(0xc00015e900, 0xc0000eb400, 0x510d5a)
        /home/guillaume/code/misc/pebble/internal/overlord/servstate/manager.go:100 +0x38
github.com/canonical/pebble/internal/overlord/servstate.(*ServiceManager).acquirePlan(0xc00015e900, 0xc00021e330, 0x16, 0x0)
        /home/guillaume/code/misc/pebble/internal/overlord/servstate/manager.go:216 +0xe9
github.com/canonical/pebble/internal/overlord/servstate.(*ServiceManager).DefaultServiceNames(0xc00015e900, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/guillaume/code/misc/pebble/internal/overlord/servstate/manager.go:316 +0x62
github.com/canonical/pebble/internal/daemon.v1PostServices(0xd11da0, 0xc00021c300, 0x0, 0x0, 0x0)
        /home/guillaume/code/misc/pebble/internal/daemon/api_services.go:78 +0x1734
github.com/canonical/pebble/internal/daemon.(*Command).ServeHTTP(0xd11da0, 0x9ff060, 0xc0002360e0, 0xc00021c300)
        /home/guillaume/code/misc/pebble/internal/daemon/daemon.go:260 +0x607
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001900c0, 0x9ff060, 0xc0002360e0, 0xc00021c100)
        /home/guillaume/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xe2
github.com/canonical/pebble/internal/daemon.logit.func1(0x9ff3e0, 0xc00024c000, 0xc00021c100)
        /home/guillaume/code/misc/pebble/internal/daemon/daemon.go:331 +0xde
net/http.HandlerFunc.ServeHTTP(0xc00013d700, 0x9ff3e0, 0xc00024c000, 0xc00021c100)
        /usr/lib/go-1.13/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc0001e2000, 0x9ff3e0, 0xc00024c000, 0xc00021c100)
        /usr/lib/go-1.13/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00023a000, 0xa00b20, 0xc000222040)
        /usr/lib/go-1.13/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/lib/go-1.13/src/net/http/server.go:2928 +0x384
2022-08-08T17:08:36.115Z [pebble] Cannot start default services: cannot communicate with server: Post http://localhost/v1/services: EOF
```

And then I cannot ctrl-c anymore I have to send a sigkill. Is my config supposed to be "legal"?
