### ISSUE TITLE
Add support for a delay before starting health checks

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/pebble#145]
It would be useful to have ability to specify a delay before start executing them analogous to kubernetes' [initialDelaySeconds](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes):

```
checks:
    up:
        override: replace
        level: alive
        period: 10s
        timeout: 3s
        threshold: 3
        delay: 0s # this would be the new parameter
        exec:
            command: service nginx status
```
