### ISSUE TITLE
Reconsider checks reporting "up" status before being executed

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/pebble#164]
### Problem

If we list the checks very early in the lifetime of the Pebble plan, the output will return a default misleading "up" status, even though we aren't yet capable of making such an assessment.

### Reproduce

Use an intentionally faulty check, like:

```yaml
checks:
    chk1:
        override: replace
        level: ready
        http:
            url: http://23234sdffsdfsadf.com/
```

Start the server: `pebble run`

Immediately list the checks with `pebble checks`, and the output will be

```
Check  Level  Status  Failures
chk1   ready  up      0/3
```

Notice the `Status = up`, which is misleading, and will eventually switch to "down".

**Comment by benhoyt** [comment]
This is a good point. It will mean before Pebble starts the `/v1/health` endpoint (used as a K8s probe endpoint by Juju) will return an error as it should, then when Pebble starts it'll report success (`up`), then if the check is actually down, it'll report `down` correctly after N failures. But in the meantime we have a "blip" of up. I originally designed it to default to `up` as kind of a "give it the benefit of the doubt".

I'm not sure we should just change the default to `down`, because we don't really want it to stay down for a full 10s (the default check period). We could add a third state `unknown` and default to that, however, that still has issues for `/v1/health` which returns an overall true/false binary result, and again I'm not sure you'd want that to report health=false for a 10 full seconds. Or maybe that is okay? For Juju we set the K8s probes' `InitialDelaySeconds` to 30s, so it would work fine for that.

We could make the check manager run the checks right away ... but that isn't right either, because the service/workload being monitored probably isn't up yet anyway.

@hpidcock Thoughts?

**Comment by hpidcock** [comment]
I don't think "up" is correct initially, but I'm also not sure defaulting to "down" is correct either. My instinct is to make the default state configurable with "down" as the default.

**Comment by hpidcock** [comment]
```
checks:
    chk1:
        override: replace
        level: ready
        initial-status: down
        http:
            url: http://23234sdffsdfsadf.com/
```
