### ISSUE TITLE
Pebble not passing configured environment variables to services

### ISSUE THREAD

**Issue by jnsgruk** [canonical/pebble#17]
When testing out the config of a new Pebble-based charm, it seems to not be passing env variables to child processes.

A simple test (these files are uploaded to this issue - including the built pebble binary I'm using) :

Dockerfile:

```Dockerfile
FROM ubuntu:focal

ENV PEBBLE /config

COPY pebble /usr/bin/pebble
COPY pebble-test /usr/bin/pebble-test
COPY 000-test-layer.yaml /config/layers/000-test-layer.yaml

CMD ["/usr/bin/pebble", "run"]
```

pebble-test:

```bash
#!/bin/bash
if [[ -z "${MYVAR:-}" ]]; then
  echo "Variable MYVAR is unset" > /tmp/out.log
else
  echo "The value of MYVAR is: ${MYVAR}" > /tmp/out.log
fi
```

000-test-layer.yaml

```yaml
---
summary: Test Layer

services:
  pebbletest:
    override: replace
    summary: Simple test layer
    command: /usr/bin/pebble-test
    default: start
    environment:
      - MYVAR: my-very-important-value
```

The following commands then illustrate the issue:

```bash
$ docker build -t jnsgruk/pebble-test:latest .
$ docker run -d --name pbl --rm -it jnsgruk/pebble-test:latest
$ docker exec -it pbl cat /tmp/out.log
Variable MYVAR is unset

# Cleanup: docker stop pbl
```

Thanks :)

[pebble-env-issue-test.zip](https://github.com/canonical/pebble/files/6170049/pebble-env-issue-test.zip)
