### ISSUE TITLE
Pebble does not try to restart service if exited too quickly for the first time

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/pebble#240]
Hello,
we face the following issue:
our charm service is dependent on another service (2nd charm) to be alive. When we deploy bundle we cannot guarantee that 2nd charm will go alive before main charm.

What happens:
1. Charm 1 installs first
2. Charm 1 tries to start pebble service
3. Charm 2 is not yet alive
4. Service exits with error since tries to connect to charm 2 which is not alive (exited to quickly)
5. Charm 2 goes UP
6. Charm 1 never recovers since pebble tries to start the service only once

We tried to define health checks, but it looks like if the service was not start for the first time, then health checks are ignored.

Can we control from pebble retry interval and force it to try to start the service again?
We do not want to do service management on charm side and prefer to rely on Pebble in this scenario

please see related issue in the repo: https://github.com/canonical/kfp-operators/issues/220

**Comment by jnsgruk** [comment]
> Can we control from pebble retry interval and force it to try to start the service again?

There are a bunch of controls you have over the restarting of a service:

```yaml
services:
	    # (Optional) Defines what happens when the service exits with a nonzero
        # exit code. Possible values are: "restart" (default) which restarts
        # the service after the backoff delay, "shutdown" which shuts down and
        # exits the Pebble server, and "ignore" which does nothing further.
        on-failure: restart | shutdown | ignore

        # (Optional) Defines what happens when each of the named health checks
        # fail. Possible values are: "restart" (default) which restarts
        # the service once, "shutdown" which shuts down and exits the Pebble
        # server, and "ignore" which does nothing further.
        on-check-failure:
            <check name>: restart | shutdown | ignore

        # (Optional) Initial backoff delay for the "restart" exit action.
        # Default is half a second ("500ms").
        backoff-delay: <duration>

        # (Optional) After each backoff, the backoff delay is multiplied by
        # this factor to get the next backoff delay. Must be greater than or
        # equal to one. Default is 2.0.
        backoff-factor: <factor>

        # (Optional) Limit for the backoff delay: when multiplying by
        # backoff-factor to get the next backoff delay, if the result is
        # greater than this value, it is capped to this value. Default is
        # half a minute ("30s").
        backoff-limit: <duration>

        # (Optional) The amount of time afforded to this service to handle
        # SIGTERM and exit gracefully before SIGKILL terminates it forcefully.
        # Default is 5 seconds ("5s").
        kill-delay: <duration>
```

Have you tried any of those? :)

**Comment by cjdcordeiro** [comment]
I believe this is related to the fact that Pebble does not support one-shot services (and maybe also a bug as IMO, regardless of the service's nature, Pebble should catch its errors). Something similar was initially reported [here](https://github.com/canonical/pebble/issues/37) and implemented via `pebble exec`, without ever altering the nature of the supported commands for Pebble services.

Although this could be worth a discussion, I think the most immediate workaround for that issue is to force a `sleep`.

**Comment by phoevos** [comment]
@jnsgruk, I did try the available options: 
* `on-failure` seemed the most promising one. I've tried it (either as the default or explicitly setting it), but it looks like since the service is considered inactive (and not failed) this is never triggered. I believe that this is implied in the description:

  > when the service exits with a nonzero exit code _given that the failure did not occur within less than 1 second_
* `on-check-failure` has been the one we've been trying to use along with our health checks. Again, this doesn't work for inactive services.
* the `backoff` options all control the behaviour between **restarts**. Won't make a difference if the service hasn't even started from the perspective of Pebble.

**Comment by ca-scribner** [comment]
imo this is different from one-shot commands.  one-shot commands are intended to be single execution.  The problem here is that a long-running service may legitimately error out quickly and users will expect pebble to restart it.  

This is typical in kubernetes controllers.  Commonly you create a controller and some configmaps that the controller needs at the same time.  If the controller wins the race and starts before the configmaps, it errors out and k8s restarts it again soon.

**Comment by benhoyt** [comment]
Yes, @ca-scribner is correct: this is not related to exec (one-shot commands), as @beliaev-maksim is describing a long-running service, just one that exits quickly if it can't connect to a dependency.

This is actually happening by design: when you start a service manually, with `pebble start` or `ops.Container.start()`, it waits up to 1 second for the service to be started. If the service exits quickly (within 1s), the `start` operation returns an error / raises an exception, and the idea is that you'd handle it there. So if you were calling `container.start('mysvc')` manually in the charm, the charm hook would raise an error and presumably Juju would try it again, so you'd get retry behaviour that way.

Similar with `replan`, which is what it looks like you're doing in the charm you linked. You're calling [`update_layer`](https://github.com/canonical/charmed-kubeflow-chisme/blob/523fb65469ed2696bf39a287a734c817fac7c0d1/src/charmed_kubeflow_chisme/pebble/_update_layer.py#L13) to add a layer and call `replan`. This will raise a `pebble.ChangeError` in the case of a service which exits too quickly, which `update_layer` turns into an `ErrorWithStatus` exception. However, this is [then caught](https://github.com/canonical/kfp-operators/blob/b19cf459b6974e839280f52501b3268ad37647d7/charms/kfp-api/src/charm.py#L674-L677) by the charm and the hook sets an error status but *returns successfully*:

```python
        except ErrorWithStatus as err:
            self.model.unit.status = err.status
            self.logger.error(f"Failed to handle {event} with error: {err}")
            return
```

This means Juju won't retry the hook, because you've exited the Python code successfully. I think the simplest thing to do would be to change the `return` above to `raise`, to re-raise the error, forcing Juju to retry the hook a bit later, which would do the add-layer/replan thing again, and hopefully this time the other charm is working. I forget off-hand how quickly and how many times Juju retries running a hook.

There are two other options I can think of:

* Defer the event. Again, this would mean whenever the next event came through, it would re-do the add-layer/replan. But it's uncertain when the next Juju event is going to come through (the problem with defer).
* Make the service wait at least 1 second before exiting, even if case of error. This would mean the service would be "successfully started" from Pebble's point of view, and then kick in Pebble's auto-restart behaviour. 

I'd lean towards the last option, because then you get Pebble's auto-restart behaviour for free. You could either do the wait in your service's code if you have control over that, or add a simple wrapper script that waits. For example, I just tested it with this, and the service goes into the auto-restart / backoff loop as we want here:

```
services:
  srv1:
    override: replace
    command: /bin/sh -c "myservice; sleep 1.1"
    startup: enabled
```

-----

It's possible we should revisit this design. But the current idea is that either the start (or replan) fails and the error is reported that way, or if the service exits later Pebble's auto-restart behaviour kicks in. The problem with your charm's current approach is that it's catching the exception and masking the error.
