### ISSUE TITLE
Return all validation errors at once when validating in `plan.CombineLayers`

### ISSUE THREAD

**Issue by barrettj12** [canonical/pebble#251]
There are multiple issues with the following plan:
```
services:
  svc1:
    startup: enabled
checks:
  chk1:
    override: replace
```

However, when this is run through `plan.CombineLayers` (which does a series of plan validations), it only returns a single problem:
```
layer "layer-0" must define "override" for service "svc1"
```

It would be more useful *not* to exit early, run all the validation checks, and then return an error message stating **everything** that's wrong with the plan, e.g.
```
invalid plan:
- layer "layer-0" must define "override" for service "svc1"
- plan must define "command" for service "svc1"
- plan must specify one of "http", "tcp", or "exec" for check "chk1"
```

**Comment by aliamerj** [comment]
Hello,

I've set up a plan layer like this:

````yml
# ~/pebble/layers/123-some-label.yaml
services:
  svc1:
    startup: enabled
checks:
  chk1:
    override: replace
````
I mad `plan.CombineLayers`  performs all validations and display any issues. This is the output I received:
````
2023-09-02T13:02:47.227Z [pebble] POST /v1/services 974.678µs 500
2023-09-02T13:02:47.227Z [pebble] Cannot start default services: 
invalid plan:
- layer "some-label" must define "override" for service "svc1"
- plan must specify one of "http", "tcp", or "exec" for check "chk1"
````
However, there's one error message missing: `plan must define "command" for service "svc1"`. Upon investigation, I found that the loop where this error should be checked is not running because `combined.Services` is empty.

So, is this a bug that needs to be fixed, or is everything working as intended?

Thank you
