### ISSUE TITLE
Infer Pebble run arguments when configured for a single service

### ISSUE THREAD

**Issue by addyess** [canonical/pebble#354]
When using rockcraft to define a single service for the container image, the rockcraft developer is allowed to define the pebble layer for their services:

```yaml
services:
    app:
        override: replace
        command: node server.js [ extra-arguments ]
        startup: enabled
        on-success: shutdown
        on-failure: shutdown
        working-dir: /lib/node_modules/node_web_app
```

This configures pebble of course to run this `app` at startup with a command that's got some nice arguments.  All is well

until...

Let's say this service is indented to be a replacement for a very standard kubernetes service like [coredns](https://github.com/coredns/helm/blob/2ebfb3a8808974a37d79667ede867617856f9f24/charts/coredns/templates/deployment.yaml#L91-L102)

```
      containers:
      - name: "coredns"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
{{- range .Values.extraSecrets }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          readOnly: true
```

One can replace the `image` in the helm chart with the rock version ✅ 
The bug here is subtle but this image will fail to start the container -- because of the `args`

Since pebble is the entrypoint into the container -- it doesn't know what to do with the args `[ "-conf", "/etc/coredns/Corefile" ]`

Solutions:
- A rockcraft guru or pebble guru would say "just change the args to `["--args","coredns", "-conf", "/etc/coredns/Corefile" ]` and [everything will be fine](https://matrix.to/#/!NPPCseDHKRvSBMUEXN:ubuntu.com/$8e6vn6GW9ZmRgh_F0BXrYchbrsyjAcdToK78fERDYfs?via=ubuntu.com&via=matrix.org).  
- A rockcraft guru may also say "you could use a dangerous [`entrypoint-service`](https://canonical-rockcraft.readthedocs-hosted.com/en/latest/reference/rockcraft.yaml/#entrypoint-service) argument

I'd like to propose another possible solution:

Could pebble knowing it's own configuration, accept arguments if it's only managing 1 service -- and pass those arguments on to the running service in place of the default args?
