### ISSUE TITLE
Ability to run one-shot commands

### ISSUE THREAD

**Issue by jnsgruk** [canonical/pebble#37]
At present, Pebble is only capable of running daemon style processes. If a short-running process is specified in a layer, an error is returned stating the process exited too quickly.

I can see two use cases for an API that would allow the running of arbitrary commands;

1. Initial setup scripts/tasks prior to starting the "main" service in a container

A nice way to expose this could be include a `type` field under `services`, something like the following:

```yaml
services:
  setup:
    # summary, override, startup fields omitted
    type: command  # or perhaps 'one-shot'?
    before:
      - mysql
    command: /setup.sh
  
  mysql:
    # summary, override, startup fields omitted
    type: daemon
    after:
      - setup
    command: /usr/bin/mysqld
```

Should this be introduced, it should perhaps assume `daemon` if not specified, so that existing charms written using Pebble will continue to function as they currently do.

2. Throughout the charm's lifecycle, perhaps as part of an action, an API to run commands in the workload container would be helpful (and could easily be used to obviate the feature above by allowing the developer to just run commands in their `pebble_ready` handler):

```python
# ...
def _on_mysql_pebble_ready(self, event):
  container = event.workload
  result = container.run(["/path/to/bin", "--arg1", "--arg2"])
  logger.info("return code: %d", result.return_code)
  logger.info("stdout: %s ", result.stdout)
  logger.info("stderr: %s ", result.stderr)
  # ...
```

This would undoubtedly help with the sort of issues being experienced in [this PR for the mysql charm](https://github.com/canonical/mysql-operator/pull/44), and is related to [LP#1923822](https://bugs.launchpad.net/juju/+bug/1923822).
