### ISSUE TITLE
pebble logs fails when there is a long line (over 4k characters)

### ISSUE THREAD

**Issue by javierdelapuente** [canonical/pebble#376]
When running `pebble logs`, when there is a line with a log over 4KiB, it fails with the error (and does not show next lines):
```
$ PEBBLE_SOCKET=~/pebble/.pebble.socket go run ./cmd/pebble logs srv1
error: cannot read log line: bufio: buffer full
exit status 1
```

This is easily reproducible with a plan like this one: 
```
summary: Simple layer

description: |
    A better description for a simple layer.

services:
    srv1:
        override: replace
        summary: logs more than 4k characters
        command: bash -c "echo {1..1100}; echo "not available in logs"; sleep 10;"
        startup: enabled
```

Although long, this line size is not uncommon for a log. https://github.com/canonical/pebble/blob/95b73bb24eafa386ad4924abb57ffae9b5ef4501/client/logs.go#L30

An alternative to a bigger constant could be to print up to a fixed number of characters and skip the rest of the line.
