### ISSUE TITLE
notify on exit

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/pebble#593]
when using pebble to run 'oneshot' commands, it is difficult to obtain a notice when the process is exits (zero or not).

desired functionality:

```yaml
layer:
    command: /my/command && pebble notify command-done
```
I don't think that the layer's `after: [otherlayer]` functionality would cover this as it would guarantee the service is started after the first one is launched, but not after it is 'done'. 

Current best workaround we're aware of:
push a bash script containing `/my/command && pebble notify command-done` and then:

```yaml
layer:
    command: sh /myscript
```

Another way would be to craft a pebble check that keeps an eye on the process and use check-failed to be notified when it's no longer there.

# Thought 1:
```yaml
layer:
    command: /my/command 
    on-exit: pebble notify command-done
```

# Thought 2:
```yaml
layer1:
    command: /my/command 
layer2:
    after-exit: layer1
    command: pebble notify command-done
```

Side-note (in either option): 
would there be a way to obtain the exit code?
